[tool.poetry]
name = "disco"
version = "0.2.0"
description = "very simple service discovery app"
authors = ["Grzegorz Zebrowski <grzegorz.zebrowski@thrust.pl>"]

[tool.poetry.dependencies]
python = "^3.4"
redis = "^2.10"

[tool.poetry.dev-dependencies]
pytest = "^3.0"
