[tool.poetry]
name = "disco"
version = "0.1.0"
description = "very simple service discovery app"
authors = ["Grzegorz Zebrowski <grzegorz.zebrowski@thrust.pl>"]

[tool.poetry.dependencies]
python = "*"
redis = "^2.10"

[tool.poetry.dev-dependencies]
pytest = "^3.0"
